@startuml

class Tournament{


}

class Player{
   + PlayerCreate()
   + PlayerDelete()
   + getName()
   + getScore()
   + getWinMatch()
   + getAssistScore()
   + getTournamentsWin()
   + getMoneyWin()
   - String name
   - String surname
   - String DNI
   - Double score
   - Double withMatch
   - Double assistScore
   - Double tournamentsWin
   - Double moneyWin
}

class Matchmake{


}

class Team{
    + TeamAdd()
    + TeamRemove()
    + TeamCreate()
    + TeamDelete()
    -
}

class User{


}

class Administrator{


}

Tournament *-down-> Team
Team *-down-> Player
Player -down-> User
Tournament -down-> Matchmake
Matchmake -down-> Team
Matchmake -down-> Player
User <|.down. Administrator

@enduml